### ISSUE TITLE
Release Notes: Review wording of cloud-native, cloud-enabled applications

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launcher/appdev-documentation#944]
Per Ladislav's feedback:
"creating new cloud-native and cloud-enabled existing applications" sounds weird :-) I guess you meant something like "cloud-enabling existing applications", but that's horrible too.

**Comment by inoxx03** [comment]
@Ladicek I agree:) This wording sound strange. Besides, "could-enabling existing applications" (ugh!) implies brownfield developemnt, Which AFAIK is not really the intended use for RHOAR at this point (I might be wrong here but that's the info I have).

I'll rephrase that bit to make it less ... buzz-word-y:) Thanks for catching this.

**Comment by inoxx03** [comment]
I revised the wording in the Product description and opened an MR against the RN repo.

**Comment by inoxx03** [comment]
Changes merged to `master` and synced to `stage`. Marking this as resolved.
