### ISSUE TITLE
Vert.x guide contains a table of tech preview components, which duplicates release notes

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/appdev-documentation#951]

**Comment by inoxx03** [comment]
@Ladicek Thank you. Keeping this section in the runtime guide is indeed redundant. I'll file a PR to remove. We'll link to the RN instead.

**Comment by Ladicek** [comment]
FTR, there's a link to RN already.

**Comment by inoxx03** [comment]
Indeed. One less thing to worry about, I guess:)

**Comment by inoxx03** [comment]
The section has been removed in: PR #954
