### ISSUE TITLE
the list of "tested artifacts provided with WF Swarm" in release notes is incomplete

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/appdev-documentation#953]
The table _6.2.2. Tested Maven Artifacts Provided with WildFly Swarm_ in the release notes is incomplete. The complete list of "certified" fractions is:

- `arquillian`
- `archaius`
- `hystrix`
- `ribbon`
- `ribbon-secured`

**Comment by inoxx03** [comment]
@Ladicek Thank you:) I'll update the table. This list is based on information provided in  the [Suported Configurations google doc](https://docs.google.com/document/d/1nY9Ku_oUWFHj-PDdTajhjMj1DWidswbsUb7fAlcYBgY/edit) Where can I find more accurate information on which WFS fractions are certified?

**Comment by Ladicek** [comment]
I commented on that google doc yesterday -- too bad I didn't notice it earlier.

**Comment by Ladicek** [comment]
Oh and the list of "certified" fractions is in the `bom-certfied`: https://github.com/wildfly-swarm/wildfly-swarm/blob/master/boms/bom-certified/certified.conf

**Comment by inoxx03** [comment]
@Ladicek Thank you. I see it now. I'll update the list:)

**Comment by inoxx03** [comment]
@Ladicek I updated the list and merged the changes into `master` and `stage`.
